"""Frustum-overlap retrieval of past frames for spatial memory.

The causal DiT's attention window is bounded by `context_length` (16
frames, see CLAUDE.md decision log). Anything the camera saw further back
than that is invisible to plain causal attention. Spatial memory needs a
cheap, pose-only (no pixel comparison) way to decide *which* older frames
are worth pulling back into context -- this module scores candidate past
frames by how much their camera frustum overlaps the current query
frustum, using only poses and intrinsics (the same interface as
`raymap.py`), and returns the top-k indices for the caller (the DiT's
rollout loop, not this module) to actually re-inject as extra attention
tokens/KV entries.

This is a coarse recall-oriented heuristic, not exact frustum-frustum
polygon/volume intersection (which would need convex-polyhedron clipping
and is overkill for *selecting candidates* -- the transformer's cross-frame
attention still does the real fine-grained reasoning over whatever gets
retrieved). The heuristic combines three signals:

  1. Cone visibility: is either camera's center inside the other's
     (roughly conical) field of view?
  2. View-direction alignment: cameras facing the same way overlap more
     than cameras facing each other or facing away.
  3. Distance falloff: nearby cameras overlap more than distant ones, at a
     scale set by the scene extent (a config parameter, not hardcoded --
     the procedural scenes generated by `data-engineer` vary in size).

All three are combined multiplicatively into a single `[0, 1]`-ish overlap
score per (query, candidate) pair.
"""
from __future__ import annotations

from typing import Tuple

import torch


def _forward_and_position(poses: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """`poses`: (..., 4, 4) c2w. Returns (forward (..., 3), position (..., 3)).
    OpenGL convention: the camera looks down its own -Z axis, so world-space
    forward is the *negative* third column of the rotation block.
    """
    forward = -poses[..., :3, 2]
    position = poses[..., :3, 3]
    return forward, position


def _cone_half_angle(intrinsics: torch.Tensor, width: int, height: int) -> torch.Tensor:
    """Half-angle (radians) of a circular cone loosely bounding the
    rectangular pinhole frustum, taken as the half-diagonal FOV so the cone
    fully contains the (tighter, rectangular) true frustum -- a deliberate
    over-approximation, since under-counting overlap candidates is worse
    for a recall-oriented retrieval mechanism than over-counting them.
    """
    fx, fy, cx, cy = intrinsics.unbind(-1)
    # Half-diagonal in pixels, mapped through the (approximate, isotropic)
    # focal length -> angle.
    half_diag_px = 0.5 * torch.sqrt(torch.tensor(float(width) ** 2 + float(height) ** 2, device=intrinsics.device))
    f_mean = 0.5 * (fx + fy)
    return torch.atan(half_diag_px / f_mean)


def frustum_overlap_scores(
    query_pose: torch.Tensor,
    query_intrinsics: torch.Tensor,
    candidate_poses: torch.Tensor,
    candidate_intrinsics: torch.Tensor,
    width: int,
    height: int,
    distance_scale: float,
    eps: float = 1e-8,
) -> torch.Tensor:
    """Score candidate frames' frustum overlap with a single query frame.

    Args:
        query_pose: (B, 4, 4) c2w.
        query_intrinsics: (B, 4) (fx, fy, cx, cy), in `width`/`height` units.
        candidate_poses: (B, K, 4, 4) c2w, the K candidate history frames.
        candidate_intrinsics: (B, K, 4).
        width, height: resolution the intrinsics are expressed in (the raw
            render/patch-grid resolution used to derive FOV -- not tied to
            `tokens_per_frame`, since this module never touches pixels).
        distance_scale: characteristic scene scale (e.g. room diagonal) for
            the distance falloff; a config/data parameter, never hardcoded,
            since procedural scene extents vary (see `src/data/scenes.py`).

    Returns:
        (B, K) float scores in roughly [0, 1], higher = more overlap.
    """
    q_fwd, q_pos = _forward_and_position(query_pose)  # (B,3)
    c_fwd, c_pos = _forward_and_position(candidate_poses)  # (B,K,3)

    q_pos_b = q_pos.unsqueeze(1)  # (B,1,3)
    q_fwd_b = q_fwd.unsqueeze(1)  # (B,1,3)

    to_candidate = c_pos - q_pos_b  # (B,K,3): query -> candidate
    raw_dist = to_candidate.norm(dim=-1)  # (B,K)
    # A candidate at (numerically) the same position as the query has an
    # undefined query->candidate direction, but trivially total frustum
    # overlap -- flagged separately rather than left to a division by a
    # near-zero vector (which would spuriously read as "not visible").
    degenerate = raw_dist < 1e-6
    dist = raw_dist + eps
    to_candidate_dir = to_candidate / dist.unsqueeze(-1)
    to_query_dir = -to_candidate_dir

    q_half_angle = _cone_half_angle(query_intrinsics, width, height)  # (B,)
    c_half_angle = _cone_half_angle(candidate_intrinsics, width, height)  # (B,K)

    # Angle between query's forward and the direction toward the candidate:
    # is the candidate's center inside the query's cone?
    cos_q_sees_c = (q_fwd_b * to_candidate_dir).sum(-1).clamp(-1.0, 1.0)
    angle_q_sees_c = torch.acos(cos_q_sees_c)
    q_sees_c = angle_q_sees_c <= q_half_angle.unsqueeze(-1)

    # Angle between candidate's forward and the direction toward the query:
    # is the query's center inside the candidate's cone?
    cos_c_sees_q = (c_fwd * to_query_dir).sum(-1).clamp(-1.0, 1.0)
    angle_c_sees_q = torch.acos(cos_c_sees_q)
    c_sees_q = angle_c_sees_q <= c_half_angle

    visible = (q_sees_c | c_sees_q | degenerate).float()  # (B,K)

    # View-direction alignment, rescaled from [-1,1] cosine similarity to
    # [0,1] so it multiplies cleanly with the other two factors.
    direction_align = 0.5 * (1.0 + (q_fwd_b * c_fwd).sum(-1))

    distance_falloff = torch.exp(-dist / max(distance_scale, eps))

    return visible * direction_align * distance_falloff


def select_top_k(
    query_pose: torch.Tensor,
    query_intrinsics: torch.Tensor,
    history_poses: torch.Tensor,
    history_intrinsics: torch.Tensor,
    width: int,
    height: int,
    distance_scale: float,
    k: int,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Top-k history frame indices by frustum-overlap score, per batch
    element. Returns `(indices (B, k) long, scores (B, k) float)`, sorted
    descending by score. If `history_poses` has fewer than `k` frames along
    its length axis, the remainder is padded by repeating the lowest-
    scoring available index (callers that care should also check
    `history_poses.shape[1] >= k` before relying on padded slots meaning
    anything).
    """
    scores = frustum_overlap_scores(
        query_pose, query_intrinsics, history_poses, history_intrinsics, width, height, distance_scale
    )  # (B, K)
    k_eff = min(k, scores.shape[1])
    top_scores, top_idx = torch.topk(scores, k_eff, dim=1)
    if k_eff < k:
        pad_idx = top_idx[:, -1:].expand(-1, k - k_eff)
        pad_scores = top_scores[:, -1:].expand(-1, k - k_eff)
        top_idx = torch.cat([top_idx, pad_idx], dim=1)
        top_scores = torch.cat([top_scores, pad_scores], dim=1)
    return top_idx, top_scores
